name: gatekeeper
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.2.2
  dart_jsonwebtoken: ^3.3.1
  yaml: ^3.1.3
  shorebird_redis_client: ^0.0.12
  curveauth_dart:
    git:
      url: https://github.com/HayesBarber/curveauth-dart
      ref: main

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
