name: gatekeeper_crypto
description: ECC dart
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  pointycastle: ^4.0.0
  uuid: ^4.5.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
