name: gatekeeper_core
description: gatekeeper core
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  gatekeeper_crypto:
    git:
      url: https://github.com/HayesBarber/gatekeeper
      path: packages/gatekeeper_crypto
      ref: main
  uuid: ^4.5.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
