name: gatekeeper_cli
description: gatekeeper cli
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  gatekeeper_config:
    git:
      url: https://github.com/HayesBarber/gatekeeper
      path: packages/gatekeeper_config
      ref: main
  gatekeeper_core:
    git:
      url: https://github.com/HayesBarber/gatekeeper
      path: packages/gatekeeper_core
      ref: main
  gatekeeper_crypto:
    git:
      url: https://github.com/HayesBarber/gatekeeper
      path: packages/gatekeeper_crypto
      ref: main
  mason_logger: ^0.3.3

dev_dependencies:
  build_runner: ^2.8.0
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0

executables:
  gk:
