name: gatekeeper
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  gatekeeper_config:
    git:
      url: https://github.com/HayesBarber/gatekeeper
      path: packages/gatekeeper_config
      ref: main
  gatekeeper_core:
    git:
      url: https://github.com/HayesBarber/gatekeeper
      path: packages/gatekeeper_core
      ref: main
  gatekeeper_crypto:
    git:
      url: https://github.com/HayesBarber/gatekeeper
      path: packages/gatekeeper_crypto
      ref: main
  shorebird_redis_client: ^0.0.12

dev_dependencies:
  args: ^2.7.0
  dart_frog_lint: ^0.1.0
  http: ^1.6.0
  mocktail: ^1.0.3
  test: ^1.25.5
