name: gatekeeper
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  curveauth_dart:
    git:
      url: https://github.com/HayesBarber/curveauth-dart
      ref: v5.0.0
  dart_frog: ^1.1.0
  shorebird_redis_client: ^0.0.12
  uuid: ^4.5.2
  yaml: ^3.1.3

dev_dependencies:
  args: ^2.7.0
  dart_frog_lint: ^0.1.0
  http: ^1.6.0
  mocktail: ^1.0.3
  test: ^1.25.5
